apiVersion: v1
kind: Secret
metadata:
  name: renato-eleve-app-secret
  namespace: renato-eleve
type: Opaque
stringData:
  NEXT_PUBLIC_SITE_URL: "https://eleveguindastes.com.br"
  API_BASE_URL: "https://api.eleveguindastes.com.br"
  FEATURE_FLAG_NEW_UI: "true"
